<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BUR8TDF" failures="3" tests="5" name="Test1" time="45.141" errors="0" timestamp="24 Jul 2019 05:04:31 GMT">
  <testcase classname="com.nopCommercev2.testCases.TC_LoginTest_001" name="loginTest" time="11.834"/>
  <testcase classname="com.nopCommercev2.testCases.TC_LoginDDT_002" name="loginTest" time="11.208"/>
  <testcase classname="com.nopCommercev2.testCases.TC_LoginDDT_002" name="loginTest" time="5.273">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommercev2.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:39)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.nopCommercev2.testCases.TC_LoginDDT_002" name="loginTest" time="4.92">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommercev2.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:39)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.nopCommercev2.testCases.TC_LoginDDT_002" name="loginTest" time="5.423">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopCommercev2.testCases.TC_LoginDDT_002.loginTest(TC_LoginDDT_002.java:39)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test1 -->
